version: "3.8"
services:
  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  vietlawbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vietlawbot
    env_file:
      - .env
    ports:
      - "5002:5002"
    depends_on:
      - redis-stack
    volumes:
      - ./uploads:/app/uploads
      - ./plain_texts:/app/plain_texts

volumes:
  redis_data:
